name: Random Daily Commits

on:
  schedule:
    - cron: "0 18 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make 5-10 random commits
        run: |
          git config user.name "sid-kx"
          git config user.email "sidkam127@gmail.com"

          COMMITS=$((5 + RANDOM % 6))

          echo "Making $COMMITS commits today"

          for ((i=1; i<=COMMITS; i++))
          do
            echo "$(date) - update $i" >> daily-activity.txt
            git add daily-activity.txt
            git commit -m "Daily update $i"
          done

          git push
